### ISSUE TITLE
CII: BR-61 test bug

### ISSUE THREAD

**Issue by AndreasPvd** [phax/validation#396]
Hi everyone,

There are two related bugs in the current BR-61 test for CII:

1) The **BR-61** in EN16931-model.sch is in the context "$**Payment_instructions**". This is wrong. It should be in the context "$**CreditTransfer_information**".

So, please change
`<rule context="$Payment_instructions ">`
`    <assert test="$BR-49" flag="fatal" id="BR-49">[BR-49]-A Payment instruction (BG-16) shall specify the Payment means type code (BT-81).</assert>`
`    <assert test="$BR-61" flag="fatal" id="BR-61">[BR-61]-If the Payment means type code (BT-81) means SEPA credit transfer, Local credit transfer or Non-SEPA international credit transfer, the Payment account identifier (BT-84) shall be present.</assert>
`
`</rule>`

to 

`<rule context="$Payment_instructions ">`
`    <assert test="$BR-49" flag="fatal" id="BR-49">[BR-49]-A Payment instruction (BG-16) shall specify the Payment means type code (BT-81).</assert>`
`  </rule>`
`<rule context="$CreditTransfer_information ">`
`    <assert test="$BR-61" flag="fatal" id="BR-61">[BR-61]-If the Payment means type code (BT-81) means SEPA credit transfer, Local credit transfer or Non-SEPA international credit transfer, the Payment account identifier (BT-84) shall be present.</assert>`
`  </rule>`

2) "$CreditTransfer_information" is incorrect and currently not used. It states
`<param name="CreditTransfer_information " value="//ram:SpecifiedTradeSettlementPaymentMeans[ram:TypeCode='30' or ram:TypeCode='58']/ram:PayerPartyDebtorFinancialAccount"/>`

but it should be
`<param name="CreditTransfer_information " value="//ram:SpecifiedTradeSettlementPaymentMeans[ram:TypeCode='30' or ram:TypeCode='58']/ram:PayeePartyCreditorFinancialAccount"/>`

(**Payee**Party**Creditor**... instead of **Payer**Party**Debtor**...) Currently it is checking for BT-91 instead of BT-84.

Thanks a lot, 
Andreas

**Comment by oriol** [comment]
point 1 was already resolved.

**Comment by AP-G** [comment]
Unfortunately, it was NOT resolved:

In version 1.3.13:
`<param name="CreditTransfer_information " value="//ram:SpecifiedTradeSettlementPaymentMeans[ram:TypeCode='30' or ram:TypeCode='58']/ram:Paye`**r**`Party`**Debtor**`FinancialAccount"/>`

In version 1.3.14:
`<param name="CreditTransfer_information " value="//ram:SpecifiedTradeSettlementPaymentMeans[ram:TypeCode='30' or ram:TypeCode='58']/ram:Paye`**e**`PartyDebtorFinancialAccount"/>`

**This xPath does not exist in CII at all.**

Correct (as shown in the original post):
`<param name="CreditTransfer_information " value="//ram:SpecifiedTradeSettlementPaymentMeans[ram:TypeCode='30' or ram:TypeCode='58']/ram:Paye`**e**`Party`**Creditor**`FinancialAccount"/>`

This should be a hotfix as well, as else BR-50 and BR-61 do not work anymore.

**Comment by oriol** [comment]
Corrected in the hot fix release. Thanks for spotting it @AP-G !

**Comment by csautereau** [comment]
The Validation artefact I have just updated from https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931#RegistryofsupportingartefactstoimplementEN16931-Validationartefacts

still have the same error

   <rule context="//ram:SpecifiedTradeSettlementPaymentMeans[ram:TypeCode='30' or ram:TypeCode='58']/**ram:PayeePartyDebtorFinancialAccount">**
     
 <assert id="BR-50" flag="fatal" test="(ram:IBANID) or (ram:ProprietaryID)">[BR-50]-A Payment account identifier (BT-84) shall be present if Credit transfer (BG-16) information is provided in the Invoice.</assert>
      <assert id="BR-61" flag="fatal" test="(ram:IBANID) or (ram:ProprietaryID)">[BR-61]-If the Payment means type code (BT-81) means SEPA credit transfer, Local credit transfer or Non-SEPA international credit transfer, the Payment account identifier (BT-84) shall be present.</assert>
    </rule>


ram:PayeePartyDebtorFinancialAccoun should be replaced with ram:PayeePartyCreditorFinancialAccount

Is it corrected or not, and where ?

**Comment by csautereau** [comment]
In fact it seems that this control is done with rule BR-CO-27 (which is a new one ?!)

    <rule context="//ram:SpecifiedTradeSettlementPaymentMeans">
      <assert id="BR-49" flag="fatal" test="(ram:TypeCode)">[BR-49]-A Payment instruction (BG-16) shall specify the Payment means type code (BT-81).</assert>

      <assert id="BR-CO-27" flag="fatal" test="(ram:PayeePartyCreditorFinancialAccount/ram:IBANID or ram:PayeePartyCreditorFinancialAccount/ram:ProprietaryID) and not(ram:PayeePartyCreditorFinancialAccount/ram:IBANID and ram:PayeePartyCreditorFinancialAccount/ram:ProprietaryID)">[BR-CO-27]- Either the IBAN or a Proprietary ID (BT-84) shall be used.</assert>
    </rule>

Is it right ?

**Comment by csautereau** [comment]
BR-CO-27 only forces the presence of IBAN of Bank account in any invoice ? whatever the Payment pean code ??
Is it an anticipation of ViDA ?

I do not see the same BR-CO-27 rule in UBL schematron. Don't you try to correct rule BR-61 with this new one, which is wrong also, but close to right if you add a condition on Payment means codes 30 and 58

**Comment by csautereau** [comment]
After more exchange : the rules are BR-50 and BR-61, which forces to have a BT-84 (IBAN) or BT-84-0 (Bank Account) for Credit Transfer. The specificity in COO is that there are 2 BT for a Bank Account. We could add a rule saying that they are mutually exclusive (which is BR-CO-27 which shroud not be named that way as it is specific to CII)

We should correct the BR

    <rule context="//ram:SpecifiedTradeSettlementPaymentMeans[ram:TypeCode='30' or ram:TypeCode='58']/ram:PayeePartyCreditorFinancialAccount">

      <assert id="BR-50" flag="fatal" test="(ram:IBANID) or (ram:ProprietaryID)">[BR-50]-A Payment account identifier (BT-84) shall be present if Credit transfer (BG-16) information is provided in the Invoice.</assert>

      <assert id="BR-61" flag="fatal" test="(ram:IBANID) or (ram:ProprietaryID)">[BR-61]-If the Payment means type code (BT-81) means SEPA credit transfer, Local credit transfer or Non-SEPA international credit transfer, the Payment account identifier (BT-84) shall be present.</assert>

    </rule>

With (if we want to make directly BT-84 and BT-84-0 mutually exclusive (no need for BR-CO-27 then)

    <rule context="//ram:SpecifiedTradeSettlementPaymentMeans[ram:TypeCode='30' or ram:TypeCode='58']">

      <assert id="BR-50" flag="fatal" test="(ram:PayeePartyCreditorFinancialAccount/ram:IBANID or ram:PayeePartyCreditorFinancialAccount/ram:ProprietaryID) and not(ram:PayeePartyCreditorFinancialAccount/ram:IBANID and ram:PayeePartyCreditorFinancialAccount/ram:ProprietaryID)">[BR-50]-A Payment account identifier (BT-84) shall be present if Credit transfer (BG-16) information is provided in the Invoice.</assert>

      <assert id="BR-61" flag="fatal" test="(ram:PayeePartyCreditorFinancialAccount/ram:IBANID or ram:PayeePartyCreditorFinancialAccount/ram:ProprietaryID) and not(ram:PayeePartyCreditorFinancialAccount/ram:IBANID and ram:PayeePartyCreditorFinancialAccount/ram:ProprietaryID)">[BR-61]-If the Payment means type code (BT-81) means SEPA credit transfer, Local credit transfer or Non-SEPA international credit transfer, the Payment account identifier (BT-84) shall be present.</assert>  

    </rule>

Or if we want to keep BR-CO-27 for mutual exclusion

    <rule context="//ram:SpecifiedTradeSettlementPaymentMeans[ram:TypeCode='30' or ram:TypeCode='58']">

      <assert id="BR-50" flag="fatal" test="ram:PayeePartyCreditorFinancialAccount/ram:IBANID or ram:PayeePartyCreditorFinancialAccount/ram:ProprietaryID">[BR-50]-A Payment account identifier (BT-84) shall be present if Credit transfer (BG-16) information is provided in the Invoice.</assert>

      <assert id="BR-61" flag="fatal" test="ram:PayeePartyCreditorFinancialAccount/ram:IBANID or ram:PayeePartyCreditorFinancialAccount/ram:ProprietaryID">[BR-61]-If the Payment means type code (BT-81) means SEPA credit transfer, Local credit transfer or Non-SEPA international credit transfer, the Payment account identifier (BT-84) shall be present.</assert>  


KR
