### ISSUE TITLE
Simple website link issues

### ISSUE THREAD

**Issue by AndreasPvd** [phax/validation#401]
1. The link on https://github.com/ConnectingEurope/eInvoicing-EN16931 to the current validation artefacts is not correct. It leads to an empty page. The correct link is https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/tag/validation-1.3.13
2. The link to UBL validation artefacts on the EC page is not correct. It links to the codelist excel version 14

BR,
Andreas

**Comment by phax** [comment]
@AndreasPvd  thanks. The first entry was fixed - the edifact syntax now points to the correct tag. For CII and UBL it was already fine.
We are not responsible for links on the EC page itself - please file a ticket there.
hth

**Comment by AndreasPvd** [comment]
@phax Unfortunately, the first entry is still wrong:
![b1](https://github.com/user-attachments/assets/5b33f064-0ad3-49e4-b180-da16c0e59db3)
![b2](https://github.com/user-attachments/assets/6653166e-47d6-495b-87b9-6d5df53eb0d6)
About EC: It states to please use this GitHub to state any issue. - And I was more than once given a clear hint to use is place  when I tried to use the service desk before...

**Comment by phax** [comment]
Thanks - seems like GitHub changed the way they handle milestones. Fixed.

Regarding the second link: sorry, I misread the issue. 
The text in the readme says:
> Digital Europe supported code lists are available here:

and the page does contain the required information. I don't see the issue.

**Comment by AndreasPvd** [comment]
Have a look at the link. UBL links to codelist and not to validation artefacts.
![b3](https://github.com/user-attachments/assets/e3d07931-c503-4058-9653-8705fbd87dea)

**Comment by phax** [comment]
@midran  please have a look at what Andreas mentioned above

**Comment by midran** [comment]
Fixed, @phax @AndreasPvd please verify

**Comment by AndreasPvd** [comment]
Thanks a lot!
